version: '3.5'
services:
    traefik:
        build: ./traefik
        container_name: traefik
        dns:
            - 10.10.10.10
        ports:
            - '80:80'
            - '443:443'
            - '8080:8080'
        volumes:
            - '/var/log/traefik:/var/log/traefik'
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/opt/traefik:/etc/trafike'
